# Generated by Django 3.2.8 on 2021-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaii', '0006_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(default='Awesome BLogs', max_length=255)),
                ('body', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
