# Generated by Django 3.2.8 on 2021-11-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsaii', '0011_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='byline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='img2',
        ),
        migrations.AddField(
            model_name='event',
            name='title_tag',
            field=models.CharField(default='Spectacular Events', max_length=255),
        ),
        migrations.AlterField(
            model_name='evecomm',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evecomm', to='dsaii.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default='Enter date of event', max_length=255),
        ),
    ]
